import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BookProvider } from "@/context/bookContext";
import { BookChapterProvider } from "@/context/bookChapterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <BookChapterProvider>
        <BookProvider>
          <body className={inter.className}>{children}</body>
        </BookProvider>
      </BookChapterProvider>
    </html>
  );
}
